### Site Settings ###
title               : Sangwoo's  blog
description         : >-
                      Sangwoo Noh
                      
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
#repository          : YoussefRaafatNasry/portfolYOU     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Sangwoo Noh
  image             : https://avatars2.githubusercontent.com/u/16892436?s=460&u=30c2e125ca2aa6c4183bed0dfbd73380a05ca291&v=4
# behance           : your_username
# dribbble          : your_username
  email             : sw79899@gmail.com
#  facebook          : your_username
  github            : garyGitgit
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : garynoh
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
#collections:
#  projects:
#    output: true
#    permalink: /projects/:name
  #activities:
  #  output: true
  #  permalink: /activities/:name  

### Disqus ###
#disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
#  - scope:
#      path: ""
#      type: "projects"
#    values:
#      layout: "page"
#  - scope:
#      path: ""
#      type: "activities"
#    values:
#      layout: "page"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
